apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direktiv.fullname" . }}-api
  labels:
    {{- include "direktiv.labelsAPI" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "direktiv.selectorLabelsAPI" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "direktiv.selectorLabelsAPI" . | nindent 8 }}
        app: {{ include "direktiv.fullname" . }}-flow
    spec:
      {{- if gt (default $.Values.api.replicas 1) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - direktiv-api
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "direktiv.serviceAccountName" . }}
      containers:
{{- if .Values.opentelemetry.enabled }}
{{ include "direktiv.opentelemetry" . | indent 8 }}
{{- end }}
{{- if .Values.api.extraContainers }}
{{ toYaml .Values.api.extraContainers | indent 8}}
{{- end }}
        - name: api
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: {{ .Values.api.resources.requests.memory }}
            limits:
              memory: {{ .Values.api.resources.limits.memory }}
          image: "{{ .Values.registry }}/{{ .Values.api.image }}:{{ .Values.api.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/bin/direktiv", "-c", "/config/api-config.yaml"]
          volumeMounts:
          {{- if .Values.api.extraVolumeMounts -}}
          {{ toYaml .Values.api.extraVolumeMounts | nindent 10 }}
          {{- end }}
          - name: flow-config
            mountPath: /etc/direktiv/flow-config.yaml
            subPath: flow-config.yaml
          ports:
            - name: api
              containerPort: 1644
              protocol: TCP
          env:
          {{- if .Values.api.additionalEnvs }}
          {{- toYaml .Values.api.additionalEnvs | nindent 10 }}
          {{- end }}
          - name: DIREKTIV_APP
            value: "api"
          - name: DIREKTIV_LOG_JSON
            value: {{ .Values.logging | quote }}
          - name: DIREKTIV_DEBUG
            value: {{ .Values.debug | quote }}
          - name: DIREKTIV_SERVICE_NAMESPACE
            value: {{ .Values.functions.namespace }}
          {{- if or (ne .Values.http_proxy "") (ne .Values.https_proxy "") }}
          - name: "HTTP_PROXY"
            value: "{{ .Values.http_proxy }}"
          - name: "HTTPS_PROXY"
            value: "{{ .Values.https_proxy }}"
          - name: "NO_PROXY"
            value: "{{ .Values.no_proxy }}"
          {{- end }}
          - name: "DIREKTIV_NAMESPACE"
            value: "{{ .Release.Namespace }}"
          - name: "DIREKTIV_HOST"
            value: "{{ .Values.ingress.host }}"
          - name: DIREKTIV_DB
            valueFrom:
              secretKeyRef:
                name: {{ include "direktiv.fullname" . }}
                key: db
      volumes:
        {{- if .Values.api.extraVolumes }}
        {{ toYaml .Values.api.extraVolumes | nindent 8 }}
        {{- end }}
{{- if .Values.opentelemetry.enabled }}
{{ include "direktiv.opentelemetry.volume" . | indent 8 }}
{{- end }}
        - name: flow-config
          configMap:
            name: {{ include "direktiv.fullname" . }}-config-flow
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
