apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "direktiv.fullname" . }}-ingress-api
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.timeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.timeout }}"
    {{- if ne .Values.ingress.certificate "none" }}
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    {{- if .Values.apikey }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($apikey_is_ok != 1) {
      return 401;
      }
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if ne .Values.ingress.certificate "none" }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.certificate }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: {{ include "direktiv.fullname" . }}-api
              port:
                number: 8080
