{{- if .Values.ui.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direktiv.fullname" . }}-ui
  labels:
    {{ include "direktiv.labelsUI" . | nindent 4 }}-ui
spec:
  replicas: {{ .Values.ui.replicas }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "direktiv.selectorLabelsUI" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "direktiv.selectorLabelsUI" . | nindent 8 }}
    spec:
    {{- if gt (default $.Values.ui.replicas 1) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values: 
                  - direktiv-ui
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "direktiv.serviceAccountName" . }}
      containers:
{{- if .Values.ui.extraContainers }}
{{ toYaml .Values.ui.extraContainers | indent 8 }}
{{- end }}
        - name: ui
          volumeMounts:
          - mountPath: /var/run
            name: tmpfs-nginx
          - mountPath: /var/cache/nginx
            name: tmpfs-nginx-cache
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: {{ .Values.ui.containers.ui.resources.requests.memory }}
            limits:
              memory: {{ .Values.ui.containers.ui.resources.limits.memory }}
          image: "{{ .Values.registry }}/{{ .Values.ui.image }}:{{ .Values.ui.tag | default .Chart.AppVersion }}"
          env:
          - name: SERVE_PORT
            value: "1644"
          - name: SERVE_ADDRESS
            value: "0.0.0.0"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: ui
              containerPort: 1644
              protocol: TCP
      volumes:
      - name: tmpfs-nginx
        emptyDir: {}
      - name: tmpfs-nginx-cache
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}